// Package mesh owns the agent's WireGuard identity and peer configuration.
// v0 is coordination-plane only: the key never leaves the host, the control
// plane never sees more than the public key, and tunnel bring-up is an
// optional extra on Linux.
package mesh

import (
	"context"
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const keyFile = "wg.key"

// ConfigFile is the rendered wg-quick config; the basename doubles as the
// interface name (`wg-quick up …/sigma0.conf` → sigma0).
const ConfigFile = "sigma0.conf"

// LoadOrCreateKey returns the host's Curve25519 keypair (base64), generating
// and persisting the private key (0600) on first run. Pure stdlib — no `wg`
// CLI involved.
func LoadOrCreateKey(dataDir string) (privB64, pubB64 string, err error) {
	curve := ecdh.X25519()
	path := filepath.Join(dataDir, keyFile)

	b, err := os.ReadFile(path)
	switch {
	case err == nil:
		raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(b)))
		if err != nil {
			return "", "", fmt.Errorf("corrupt mesh key %s: %w", path, err)
		}
		priv, err := curve.NewPrivateKey(raw)
		if err != nil {
			return "", "", fmt.Errorf("corrupt mesh key %s: %w", path, err)
		}
		return strings.TrimSpace(string(b)), base64.StdEncoding.EncodeToString(priv.PublicKey().Bytes()), nil
	case errors.Is(err, fs.ErrNotExist):
		priv, err := curve.GenerateKey(rand.Reader)
		if err != nil {
			return "", "", err
		}
		privB64 = base64.StdEncoding.EncodeToString(priv.Bytes())
		if err := os.MkdirAll(dataDir, 0o700); err != nil {
			return "", "", err
		}
		if err := os.WriteFile(path, []byte(privB64+"\n"), 0o600); err != nil {
			return "", "", err
		}
		return privB64, base64.StdEncoding.EncodeToString(priv.PublicKey().Bytes()), nil
	default:
		return "", "", err
	}
}

// Peer mirrors the control plane's mesh peer shape.
type Peer struct {
	ServerID string  `json:"serverId"`
	Name     string  `json:"name"`
	Pubkey   string  `json:"pubkey"`
	MeshIP   string  `json:"meshIp"`
	Endpoint *string `json:"endpoint"`
}

// RenderConfig produces a wg-quick style config for this host and its peers.
func RenderConfig(privB64, selfMeshIP string, peers []Peer) string {
	var b strings.Builder
	b.WriteString("# Generated by sigmad — do not edit; rewritten on peer changes.\n")
	b.WriteString("[Interface]\n")
	fmt.Fprintf(&b, "PrivateKey = %s\n", privB64)
	fmt.Fprintf(&b, "Address = %s/16\n", selfMeshIP)
	b.WriteString("ListenPort = 51820\n")
	for _, p := range peers {
		b.WriteString("\n[Peer]\n")
		fmt.Fprintf(&b, "# %s (%s)\n", p.Name, p.ServerID)
		fmt.Fprintf(&b, "PublicKey = %s\n", p.Pubkey)
		fmt.Fprintf(&b, "AllowedIPs = %s/32\n", p.MeshIP)
		if p.Endpoint != nil && *p.Endpoint != "" {
			fmt.Fprintf(&b, "Endpoint = %s\n", *p.Endpoint)
		}
		b.WriteString("PersistentKeepalive = 25\n")
	}
	return b.String()
}

// WriteConfig persists the rendered config (0600 — it embeds the private
// key), returning its path and whether the content actually changed.
func WriteConfig(dataDir, content string) (path string, changed bool, err error) {
	path = filepath.Join(dataDir, ConfigFile)
	if prev, err := os.ReadFile(path); err == nil && string(prev) == content {
		return path, false, nil
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return "", false, err
	}
	return path, true, os.Rename(tmp, path)
}

// Apply brings the rendered config up via wg-quick. v0 scaffolding: Linux
// only, config-only everywhere else; a missing wg-quick is reported, not
// fatal, so the coordination plane keeps running.
func Apply(ctx context.Context, log *slog.Logger, configPath string) {
	if runtime.GOOS != "linux" {
		log.Info("mesh: config-only mode (tunnel bring-up is Linux-only)", "config", configPath)
		return
	}
	if _, err := exec.LookPath("wg-quick"); err != nil {
		log.Warn("mesh: wg-quick not found; config rendered but not applied", "config", configPath)
		return
	}
	// Re-sync by down+up: idempotent for v0's small meshes.
	_ = exec.CommandContext(ctx, "wg-quick", "down", configPath).Run()
	if out, err := exec.CommandContext(ctx, "wg-quick", "up", configPath).CombinedOutput(); err != nil {
		log.Warn("mesh: wg-quick up failed", "err", err, "output", strings.TrimSpace(string(out)))
		return
	}
	log.Info("mesh: WireGuard interface applied", "config", configPath)
}
