// Package mesh owns the agent's WireGuard identity and peer configuration.
// v0 is coordination-plane only: the key never leaves the host, the control
// plane never sees more than the public key, and tunnel bring-up is an
// optional extra on Linux.
package mesh

import (
	"context"
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const keyFile = "wg.key"

// ConfigFile is the rendered wg-quick config; the basename doubles as the
// interface name (`wg-quick up …/sigma0.conf` → sigma0).
const ConfigFile = "sigma0.conf"

// LoadOrCreateKey returns the host's Curve25519 keypair (base64), generating
// and persisting the private key (0600) on first run. Pure stdlib — no `wg`
// CLI involved.
func LoadOrCreateKey(dataDir string) (privB64, pubB64 string, err error) {
	curve := ecdh.X25519()
	path := filepath.Join(dataDir, keyFile)

	b, err := os.ReadFile(path)
	switch {
	case err == nil:
		raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(b)))
		if err != nil {
			return "", "", fmt.Errorf("corrupt mesh key %s: %w", path, err)
		}
		priv, err := curve.NewPrivateKey(raw)
		if err != nil {
			return "", "", fmt.Errorf("corrupt mesh key %s: %w", path, err)
		}
		return strings.TrimSpace(string(b)), base64.StdEncoding.EncodeToString(priv.PublicKey().Bytes()), nil
	case errors.Is(err, fs.ErrNotExist):
		priv, err := curve.GenerateKey(rand.Reader)
		if err != nil {
			return "", "", err
		}
		privB64 = base64.StdEncoding.EncodeToString(priv.Bytes())
		if err := os.MkdirAll(dataDir, 0o700); err != nil {
			return "", "", err
		}
		if err := os.WriteFile(path, []byte(privB64+"\n"), 0o600); err != nil {
			return "", "", err
		}
		return privB64, base64.StdEncoding.EncodeToString(priv.PublicKey().Bytes()), nil
	default:
		return "", "", err
	}
}

// Peer mirrors the control plane's mesh peer shape.
type Peer struct {
	ServerID string  `json:"serverId"`
	Name     string  `json:"name"`
	Pubkey   string  `json:"pubkey"`
	MeshIP   string  `json:"meshIp"`
	Endpoint *string `json:"endpoint"`
}

// RenderConfig produces a wg-quick style config for this host and its peers.
func RenderConfig(privB64, selfMeshIP string, peers []Peer) string {
	var b strings.Builder
	b.WriteString("# Generated by sigmad — do not edit; rewritten on peer changes.\n")
	b.WriteString("[Interface]\n")
	fmt.Fprintf(&b, "PrivateKey = %s\n", privB64)
	fmt.Fprintf(&b, "Address = %s/16\n", selfMeshIP)
	fmt.Fprintf(&b, "ListenPort = %d\n", ListenPort)
	for _, p := range peers {
		b.WriteString("\n[Peer]\n")
		fmt.Fprintf(&b, "# %s (%s)\n", p.Name, p.ServerID)
		fmt.Fprintf(&b, "PublicKey = %s\n", p.Pubkey)
		fmt.Fprintf(&b, "AllowedIPs = %s/32\n", p.MeshIP)
		if p.Endpoint != nil && *p.Endpoint != "" {
			fmt.Fprintf(&b, "Endpoint = %s\n", *p.Endpoint)
		}
		b.WriteString("PersistentKeepalive = 25\n")
	}
	return b.String()
}

// WriteConfig persists the rendered config (0600 — it embeds the private
// key), returning its path and whether the content actually changed.
func WriteConfig(dataDir, content string) (path string, changed bool, err error) {
	path = filepath.Join(dataDir, ConfigFile)
	if prev, err := os.ReadFile(path); err == nil && string(prev) == content {
		return path, false, nil
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return "", false, err
	}
	return path, true, os.Rename(tmp, path)
}

// ifaceName is the WireGuard interface name, derived from the config basename
// (sigma0.conf → sigma0), matching wg-quick's convention.
func ifaceName() string { return strings.TrimSuffix(ConfigFile, ".conf") }

// Apply reconciles the WireGuard interface to the rendered config. v1: the
// first bring-up uses `wg-quick up`, but subsequent peer changes are applied
// incrementally with `wg syncconf` — adding/removing peers WITHOUT tearing the
// tunnel down, so an existing connection survives a peer-list change (P1-4).
// Linux only; a missing tool is reported, not fatal, so coordination keeps
// running.
func Apply(ctx context.Context, log *slog.Logger, configPath string) {
	if runtime.GOOS != "linux" {
		log.Info("mesh: config-only mode (tunnel bring-up is Linux-only)", "config", configPath)
		return
	}
	if _, err := exec.LookPath("wg-quick"); err != nil {
		log.Warn("mesh: wg-quick not found; config rendered but not applied", "config", configPath)
		return
	}
	iface := ifaceName()
	if interfaceExists(ctx, iface) {
		// Incremental peer sync — no disruptive down/up.
		if err := syncConf(ctx, iface, configPath); err != nil {
			log.Warn("mesh: incremental syncconf failed; falling back to full re-up", "err", err)
			_ = exec.CommandContext(ctx, "wg-quick", "down", configPath).Run()
			if out, err := exec.CommandContext(ctx, "wg-quick", "up", configPath).CombinedOutput(); err != nil {
				log.Warn("mesh: wg-quick up failed", "err", err, "output", strings.TrimSpace(string(out)))
			}
			return
		}
		log.Info("mesh: peers synced incrementally", "iface", iface)
		return
	}
	// First bring-up creates the interface, address and link.
	if out, err := exec.CommandContext(ctx, "wg-quick", "up", configPath).CombinedOutput(); err != nil {
		log.Warn("mesh: wg-quick up failed", "err", err, "output", strings.TrimSpace(string(out)))
		return
	}
	log.Info("mesh: WireGuard interface applied", "config", configPath)
}

// interfaceExists reports whether the WireGuard device is already up (`wg show`
// exits non-zero for an absent device).
func interfaceExists(ctx context.Context, iface string) bool {
	if _, err := exec.LookPath("wg"); err != nil {
		return false
	}
	return exec.CommandContext(ctx, "wg", "show", iface).Run() == nil
}

// syncConf applies peer changes to a live interface without a teardown.
// `wg-quick strip` yields a wg-native config (drops the Address/wg-quick keys)
// which `wg syncconf` reconciles peer-by-peer. The stripped file embeds the
// private key, so it is written 0600 and removed after.
func syncConf(ctx context.Context, iface, configPath string) error {
	stripped, err := exec.CommandContext(ctx, "wg-quick", "strip", configPath).Output()
	if err != nil {
		return fmt.Errorf("wg-quick strip: %w", err)
	}
	tmp := configPath + ".stripped"
	if err := os.WriteFile(tmp, stripped, 0o600); err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp) }()
	if out, err := exec.CommandContext(ctx, "wg", "syncconf", iface, tmp).CombinedOutput(); err != nil {
		return fmt.Errorf("wg syncconf: %w (%s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}
