// Code generated by cp/cmd/gen-server-catalog. DO NOT EDIT.
//
// The dashboard's server-type vocabulary — the type list, the resource-kind ×
// server-type availability matrix, the billing weights and the per-type
// enrollment requirements — is RENDERED from the control plane's canonical
// catalog at cp/internal/store/server_catalog.go.
//
// Editing this file by hand re-creates the defect SIGMA-198 removed: a
// dashboard offering server types the API rejects. Change the Go catalog and
// regenerate:
//
//     cd cp && go generate ./...

/**
 * sha256 of the Go catalog this file was rendered from.
 *
 * web/src/lib/hosting.test.ts recomputes it, so a control-plane edit that never
 * went through the generator fails the web suite instead of quietly shipping a
 * stale dashboard.
 */
export const CATALOG_SOURCE_SHA256 = "b43f1cb5658245e74ad00fed226e3d491e82cbd266d9ab7db2e23ae4dfbad202";

export type ServerType =
  | "general"
  | "vps"
  | "database"
  | "storage"
  | "gpu"
  | "k8s"
  | "build";

export type ResourceKind =
  | "app"
  | "postgres"
  | "mysql"
  | "mongodb"
  | "redis"
  | "s3"
  | "llm";

export type ResourceCategoryId =
  | "application"
  | "database"
  | "model"
  | "storage";

export type RequirementId =
  | "distro"
  | "arch"
  | "disk"
  | "gpu";

/** One precondition a host must meet to enroll as a type. The fact field names
 *  the agent-reported datum it is checked against, so a host that never
 *  reported it can be told which fact is missing instead of simply failing. */
export type ServerRequirement = {
  id: RequirementId;
  fact: string;
  text: string;
};

export type GpuRequirement = { vendor: string; driver: boolean };

export type ServerRequirements = {
  distros: string[];
  arches: string[];
  /** Decimal-byte floor on total disk; 0 means no floor. */
  minDiskBytes: number;
  gpu: GpuRequirement | null;
  /** The same sentences the control plane will reject a host with. */
  checks: ServerRequirement[];
};

export type ServerTypeSpec = {
  type: ServerType;
  label: string;
  hint: string;
  hosts: ResourceKind[];
  /** Why hosts is empty, so the UI never shows an unexplained dead end. */
  hostsNothingReason: string;
  /** Offered when connecting a NEW server. UI guidance, not an API rule — the
   *  control plane accepts every type in this catalog. */
  connectable: boolean;
  unitWeight: number;
  requires: ServerRequirements;
};

/** One bucket of the New Resource wizard's first screen. */
export type ResourceCategorySpec = {
  id: ResourceCategoryId;
  label: string;
  hint: string;
  /** The kinds inside it, in catalog order. Exactly one means the category is a
   *  question with a single possible answer, and the picker answers it rather
   *  than asking — see web/src/lib/wizard/steps.ts. Never empty: a card that
   *  opens an empty list is a dead end, and the control plane refuses to load
   *  a catalog containing one. */
  kinds: ResourceKind[];
};

export const SERVER_CATALOG: Record<ServerType, ServerTypeSpec> = {
  general: {
    type: "general",
    label: "General",
    hint: "Apps and databases on a machine you control end to end.",
    hosts: ["app", "postgres", "mysql", "mongodb", "redis"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
  vps: {
    type: "vps",
    label: "VPS",
    hint: "A virtualized host — same capabilities, shared tenancy and burst CPU.",
    hosts: ["app", "postgres", "mysql", "mongodb", "redis"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
  database: {
    type: "database",
    label: "Database",
    hint: "Tuned for managed database engines with production-grade settings.",
    hosts: ["postgres", "mysql", "mongodb", "redis"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 100000000000,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
        { id: "disk", fact: "diskTotalBytes", text: "At least 100 GB of disk." },
      ],
    },
  },
  storage: {
    type: "storage",
    label: "Storage",
    hint: "Large disks for S3-compatible object storage.",
    hosts: ["s3"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 500000000000,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
        { id: "disk", fact: "diskTotalBytes", text: "At least 500 GB of disk." },
      ],
    },
  },
  gpu: {
    type: "gpu",
    label: "GPU",
    hint: "NVIDIA hardware for model hosting; drivers and the runtime are managed.",
    hosts: ["llm", "app"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 4,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64"],
      minDiskBytes: 0,
      gpu: { vendor: "nvidia", driver: true },
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 CPU architecture." },
        { id: "gpu", fact: "gpu", text: "An NVIDIA GPU with a usable driver." },
      ],
    },
  },
  k8s: {
    type: "k8s",
    label: "Cluster node",
    hint: "Joined to a cluster — workloads arrive through its control plane.",
    hosts: [],
    hostsNothingReason: "Cluster nodes receive workloads from the cluster's control plane, not directly.",
    connectable: false,
    unitWeight: 2,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
  build: {
    type: "build",
    label: "Build",
    hint: "Compiles images for other servers; runs no long-lived workloads.",
    hosts: [],
    hostsNothingReason: "Build servers compile images and push them to a registry; they run no workloads.",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
};

/** Every server type, in the order the dashboard presents them. */
export const SERVER_TYPES: ServerType[] = ["general", "vps", "database", "storage", "gpu", "k8s", "build"];

export const RESOURCE_KINDS: ResourceKind[] = ["app", "postgres", "mysql", "mongodb", "redis", "s3", "llm"];

export const SERVER_TYPE_LABELS: Record<ServerType, string> = {
  general: "General",
  vps: "VPS",
  database: "Database",
  storage: "Storage",
  gpu: "GPU",
  k8s: "Cluster node",
  build: "Build",
};

export const RESOURCE_KIND_LABELS: Record<ResourceKind, string> = {
  app: "App",
  postgres: "PostgreSQL",
  mysql: "MySQL",
  mongodb: "MongoDB",
  redis: "Redis",
  s3: "Object storage",
  llm: "LLM",
};

/** Step 1 of the wizard: the categories, and the kinds each one holds. */
export const RESOURCE_CATEGORY_CATALOG: Record<ResourceCategoryId, ResourceCategorySpec> = {
  application: {
    id: "application",
    label: "Application",
    hint: "Build and deploy a repository.",
    kinds: ["app"],
  },
  database: {
    id: "database",
    label: "Database",
    hint: "A managed engine with generated credentials.",
    kinds: ["postgres", "mysql", "mongodb", "redis"],
  },
  model: {
    id: "model",
    label: "Model endpoint",
    hint: "Serve a model from the Hub on GPU hardware.",
    kinds: ["llm"],
  },
  storage: {
    id: "storage",
    label: "Object storage",
    hint: "S3-compatible buckets on a storage host.",
    kinds: ["s3"],
  },
};

/** Every category, in the order step 1 offers them. */
export const RESOURCE_CATEGORIES: ResourceCategoryId[] = ["application", "database", "model", "storage"];

/** The same membership, kind-first — what a resumed draft needs to reopen
 *  the picker on the screen the user left it on. */
export const KIND_CATEGORY: Record<ResourceKind, ResourceCategoryId> = {
  app: "application",
  postgres: "database",
  mysql: "database",
  mongodb: "database",
  redis: "database",
  s3: "storage",
  llm: "model",
};

/** One line explaining what each type is for, shown in the connect dialog. */
export const SERVER_TYPE_HINTS: Record<ServerType, string> = {
  general: "Apps and databases on a machine you control end to end.",
  vps: "A virtualized host — same capabilities, shared tenancy and burst CPU.",
  database: "Tuned for managed database engines with production-grade settings.",
  storage: "Large disks for S3-compatible object storage.",
  gpu: "NVIDIA hardware for model hosting; drivers and the runtime are managed.",
  k8s: "Joined to a cluster — workloads arrive through its control plane.",
  build: "Compiles images for other servers; runs no long-lived workloads.",
};

/** Types offered when connecting a NEW server. */
export const CONNECTABLE_SERVER_TYPES: ServerType[] = ["general", "vps", "database", "storage", "gpu", "build"];

/** Why a server type can't host anything, for an honest empty state. */
export const HOSTS_NOTHING_REASON: Partial<Record<ServerType, string>> = {
  k8s: "Cluster nodes receive workloads from the cluster's control plane, not directly.",
  build: "Build servers compile images and push them to a registry; they run no workloads.",
};

/** The availability matrix, server-first. */
export const SERVER_TYPE_HOSTS: Record<ServerType, ResourceKind[]> = {
  general: ["app", "postgres", "mysql", "mongodb", "redis"],
  vps: ["app", "postgres", "mysql", "mongodb", "redis"],
  database: ["postgres", "mysql", "mongodb", "redis"],
  storage: ["s3"],
  gpu: ["llm", "app"],
  k8s: [],
  build: [],
};

/** The same matrix, kind-first — what the deploy wizard asks. */
export const ALLOWED_SERVER_TYPES: Record<ResourceKind, ServerType[]> = {
  app: ["general", "vps", "gpu"],
  postgres: ["general", "vps", "database"],
  mysql: ["general", "vps", "database"],
  mongodb: ["general", "vps", "database"],
  redis: ["general", "vps", "database"],
  s3: ["storage"],
  llm: ["gpu"],
};

/** Billing weight per server type — what a server costs to MANAGE, never
 *  what the hardware costs; customers always bring their own infrastructure. */
export const SERVER_UNIT_WEIGHTS: Record<ServerType, number> = {
  general: 1,
  vps: 1,
  database: 1,
  storage: 1,
  gpu: 4,
  k8s: 2,
  build: 1,
};

/** Weight of an unknown/legacy type: bill as an ordinary server, never zero. */
export const DEFAULT_UNIT_WEIGHT = 1;
/** Price of one unit per month. */
export const UNIT_PRICE = 5;
/** Units included for free. Three ordinary servers still cost nothing. */
export const FREE_TIER_UNITS = 3;
export const CURRENCY = "EUR";

/** Distros the hardened onboarding path accepts. */
export const SUPPORTED_DISTROS: { id: string; label: string }[] = [
  { id: "ubuntu-22.04", label: "Ubuntu 22.04 LTS" },
  { id: "ubuntu-24.04", label: "Ubuntu 24.04 LTS" },
  { id: "debian-12", label: "Debian 12" },
];

/** Whether a server type may host a resource kind. */
export function canHost(server: ServerType, kind: ResourceKind): boolean {
  return (SERVER_TYPE_HOSTS[server] ?? []).includes(kind);
}

/** Label for a server type that may not be one — CP rows carry plain strings,
 *  and an unknown type must render as itself rather than as "undefined". */
export function serverTypeLabel(type: string): string {
  return SERVER_TYPE_LABELS[type as ServerType] ?? type;
}

/** Label for a resource kind that may not be one. */
export function resourceKindLabel(kind: string): string {
  return RESOURCE_KIND_LABELS[kind as ResourceKind] ?? kind;
}

/** The kinds inside a category, in catalog order. Never empty. */
export function kindsInCategory(id: ResourceCategoryId): ResourceKind[] {
  return RESOURCE_CATEGORY_CATALOG[id].kinds;
}

/** The category a kind sits in, or null for a string that is not a kind —
 *  restored drafts and CP rows carry plain strings. */
export function categoryForKind(kind: string): ResourceCategoryId | null {
  return KIND_CATEGORY[kind as ResourceKind] ?? null;
}

/** Billing weight of a server type. An unknown type bills as an ordinary
 *  server, never as free: a typo must not silently zero out a bill. */
export function serverUnitWeight(type: string): number {
  return SERVER_UNIT_WEIGHTS[type as ServerType] ?? DEFAULT_UNIT_WEIGHT;
}

export function isServerType(value: string): value is ServerType {
  return value in SERVER_CATALOG;
}

export function isResourceKind(value: string): value is ResourceKind {
  return value in RESOURCE_KIND_LABELS;
}
