// Code generated by cp/cmd/gen-server-catalog. DO NOT EDIT.
//
// The dashboard's server-type vocabulary — the type list, the resource-kind ×
// server-type availability matrix, the billing weights and the per-type
// enrollment requirements — is RENDERED from the control plane's canonical
// catalog at cp/internal/store/server_catalog.go, together with the kinds a
// cluster refuses (cp/internal/store/clusters.go) and the engine catalogs the
// managed-data panels describe themselves from (cp/internal/store/db_engines.go
// and cp/internal/store/s3_engines.go) and the alert event vocabulary the rules
// editor labels (cp/internal/store/alerts_store.go).
//
// Editing this file by hand re-creates the defect SIGMA-198 removed: a
// dashboard offering server types the API rejects. Change the Go catalog and
// regenerate:
//
//     cd cp && go generate ./...

/**
 * sha256 of the Go catalog this file was rendered from.
 *
 * web/src/lib/hosting.test.ts recomputes it, so a control-plane edit that never
 * went through the generator fails the web suite instead of quietly shipping a
 * stale dashboard.
 */
export const CATALOG_SOURCE_SHA256 = "6a3047d61b1a0b4c37988d1e500177f3d41b82a78b428688e7008aa3db11689a";

export type ServerType =
  | "general"
  | "vps"
  | "database"
  | "storage"
  | "gpu"
  | "k8s"
  | "build";

export type ResourceKind =
  | "app"
  | "postgres"
  | "mysql"
  | "mongodb"
  | "redis"
  | "s3"
  | "llm";

export type ResourceCategoryId =
  | "application"
  | "database"
  | "model"
  | "storage";

export type RequirementId =
  | "distro"
  | "arch"
  | "disk"
  | "gpu";

/** A resource kind provisioned as a managed database engine: for these the
 *  kind IS the engine, so this union is a subset of ResourceKind. */
export type DatabaseEngine =
  | "postgres"
  | "mysql"
  | "mongodb"
  | "redis";

/** An object-storage engine. Unlike a database engine it is NOT a resource
 *  kind: `s3` is the kind, and which engine serves it is a choice under it. */
export type S3Engine =
  | "minio"
  | "seaweedfs";

/** An inference runtime this control plane knows how to render (store.llmEngines).
 *
 *  Rendered rather than restated for the reason the S3 list is: the wizard kept
 *  a two-entry copy, so renaming or replacing the default runtime on the Go
 *  side left it sending engine "vllm" for every model whose card did not
 *  resolve — a Hub timeout, a control plane with no Hub catalogue, a pasted repo
 *  id the Hub does not know — and provisionLLMTx answered with a 422 at the end
 *  of the LLM wizard while every suite stayed green (SIGMA-278). */
export type LLMEngine =
  | "vllm"
  | "ollama";

/** An alert event the control plane can emit (store.AlertEvents).
 *
 *  A union rather than a string list, because the dashboard's rules editor
 *  labels these and its label map used to enumerate a SUBSET: payment_failed
 *  had none, so the eighth chip rendered as raw snake_case beside seven
 *  sentence-case ones, on a billing-enabled deployment, with every suite green
 *  (SIGMA-274). Typed as a union, an event added on the Go side fails
 *  tsc --noEmit at the label map that forgot it. */
export type AlertEvent =
  | "server_unreachable"
  | "server_recovered"
  | "decommission_timed_out"
  | "dsd_apply_failed"
  | "deploy_failed"
  | "backup_failed"
  | "verify_failed"
  | "cert_failed"
  | "cert_expiring"
  | "payment_failed";

/** One precondition a host must meet to enroll as a type. The fact field names
 *  the agent-reported datum it is checked against, so a host that never
 *  reported it can be told which fact is missing instead of simply failing. */
export type ServerRequirement = {
  id: RequirementId;
  fact: string;
  text: string;
};

export type GpuRequirement = { vendor: string; driver: boolean };

export type ServerRequirements = {
  distros: string[];
  arches: string[];
  /** Decimal-byte floor on total disk; 0 means no floor. */
  minDiskBytes: number;
  gpu: GpuRequirement | null;
  /** The same sentences the control plane will reject a host with. */
  checks: ServerRequirement[];
};

export type ServerTypeSpec = {
  type: ServerType;
  label: string;
  hint: string;
  hosts: ResourceKind[];
  /** Why hosts is empty, so the UI never shows an unexplained dead end. */
  hostsNothingReason: string;
  /** Offered when connecting a NEW server. UI guidance, not an API rule — the
   *  control plane accepts every type in this catalog. */
  connectable: boolean;
  unitWeight: number;
  requires: ServerRequirements;
};

/** What the control plane provisions a managed database as.
 *
 *  There is no port here, deliberately. A managed engine is published on the
 *  mesh port its server ALLOCATED (MESH_PORT_BASE and up), never on the
 *  engine's container port — demo mode printed 5432 for a product that hands
 *  out 15000+, and publishing the container port here would be inviting that
 *  back. The port travels with the resource, not with the engine. */
export type DatabaseEngineSpec = {
  engine: DatabaseEngine;
  /** The image this control plane pins. Never a floating tag: the agent's
   *  policy refuses "latest" outright, so an image shown here is one the
   *  product would actually run. */
  image: string;
  /** The connection string's shape — {username}, {password}, {host}, {port} and
   *  {database}, filled once each by databaseConnectionUrl. */
  urlTemplate: string;
};

export type S3EngineSpec = {
  engine: S3Engine;
  image: string;
  /** {host} and {port}, filled by s3EndpointUrl. */
  endpointTemplate: string;
};

/** One bucket of the New Resource wizard's first screen. */
export type ResourceCategorySpec = {
  id: ResourceCategoryId;
  label: string;
  hint: string;
  /** The kinds inside it, in catalog order. Exactly one means the category is a
   *  question with a single possible answer, and the picker answers it rather
   *  than asking — see web/src/lib/wizard/steps.ts. Never empty: a card that
   *  opens an empty list is a dead end, and the control plane refuses to load
   *  a catalog containing one. */
  kinds: ResourceKind[];
};

export const SERVER_CATALOG: Record<ServerType, ServerTypeSpec> = {
  general: {
    type: "general",
    label: "General",
    hint: "Apps and databases on a machine you control end to end.",
    hosts: ["app", "postgres", "mysql", "mongodb", "redis"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
  vps: {
    type: "vps",
    label: "VPS",
    hint: "A virtualized host — same capabilities, shared tenancy and burst CPU.",
    hosts: ["app", "postgres", "mysql", "mongodb", "redis"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
  database: {
    type: "database",
    label: "Database",
    hint: "Tuned for managed database engines with production-grade settings.",
    hosts: ["postgres", "mysql", "mongodb", "redis"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 100000000000,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
        { id: "disk", fact: "diskTotalBytes", text: "At least 100 GB of disk." },
      ],
    },
  },
  storage: {
    type: "storage",
    label: "Storage",
    hint: "Large disks for S3-compatible object storage.",
    hosts: ["s3"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 500000000000,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
        { id: "disk", fact: "diskTotalBytes", text: "At least 500 GB of disk." },
      ],
    },
  },
  gpu: {
    type: "gpu",
    label: "GPU",
    hint: "NVIDIA hardware for model hosting; drivers and the runtime are managed.",
    hosts: ["llm", "app"],
    hostsNothingReason: "",
    connectable: true,
    unitWeight: 4,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64"],
      minDiskBytes: 0,
      gpu: { vendor: "nvidia", driver: true },
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 CPU architecture." },
        { id: "gpu", fact: "gpu", text: "An NVIDIA GPU with a usable driver." },
      ],
    },
  },
  k8s: {
    type: "k8s",
    label: "Cluster node",
    hint: "Joined to a cluster — workloads arrive through its control plane.",
    hosts: [],
    hostsNothingReason: "Cluster nodes receive workloads from the cluster's control plane, not directly.",
    connectable: false,
    unitWeight: 2,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
  build: {
    type: "build",
    label: "Build",
    hint: "Compiles images for other servers; runs no long-lived workloads.",
    hosts: [],
    hostsNothingReason: "Build servers compile images and push them to a registry; they run no workloads.",
    connectable: true,
    unitWeight: 1,
    requires: {
      distros: ["ubuntu-22.04", "ubuntu-24.04", "debian-12"],
      arches: ["amd64", "arm64"],
      minDiskBytes: 0,
      gpu: null,
      checks: [
        { id: "distro", fact: "distro", text: "Runs Ubuntu 22.04 LTS, Ubuntu 24.04 LTS or Debian 12." },
        { id: "arch", fact: "arch", text: "amd64 or arm64 CPU architecture." },
      ],
    },
  },
};

/** Every server type, in the order the dashboard presents them. */
export const SERVER_TYPES: ServerType[] = ["general", "vps", "database", "storage", "gpu", "k8s", "build"];

export const RESOURCE_KINDS: ResourceKind[] = ["app", "postgres", "mysql", "mongodb", "redis", "s3", "llm"];

export const SERVER_TYPE_LABELS: Record<ServerType, string> = {
  general: "General",
  vps: "VPS",
  database: "Database",
  storage: "Storage",
  gpu: "GPU",
  k8s: "Cluster node",
  build: "Build",
};

export const RESOURCE_KIND_LABELS: Record<ResourceKind, string> = {
  app: "App",
  postgres: "PostgreSQL",
  mysql: "MySQL",
  mongodb: "MongoDB",
  redis: "Redis",
  s3: "Object storage",
  llm: "LLM",
};

/** Step 1 of the wizard: the categories, and the kinds each one holds. */
export const RESOURCE_CATEGORY_CATALOG: Record<ResourceCategoryId, ResourceCategorySpec> = {
  application: {
    id: "application",
    label: "Application",
    hint: "Build and deploy a repository.",
    kinds: ["app"],
  },
  database: {
    id: "database",
    label: "Database",
    hint: "A managed engine with generated credentials.",
    kinds: ["postgres", "mysql", "mongodb", "redis"],
  },
  model: {
    id: "model",
    label: "Model endpoint",
    hint: "Serve a model from the Hub on GPU hardware.",
    kinds: ["llm"],
  },
  storage: {
    id: "storage",
    label: "Object storage",
    hint: "S3-compatible buckets on a storage host.",
    kinds: ["s3"],
  },
};

/** Every category, in the order step 1 offers them. */
export const RESOURCE_CATEGORIES: ResourceCategoryId[] = ["application", "database", "model", "storage"];

/** The same membership, kind-first — what a resumed draft needs to reopen
 *  the picker on the screen the user left it on. */
export const KIND_CATEGORY: Record<ResourceKind, ResourceCategoryId> = {
  app: "application",
  postgres: "database",
  mysql: "database",
  mongodb: "database",
  redis: "database",
  s3: "storage",
  llm: "model",
};

/** One line explaining what each type is for, shown in the connect dialog. */
export const SERVER_TYPE_HINTS: Record<ServerType, string> = {
  general: "Apps and databases on a machine you control end to end.",
  vps: "A virtualized host — same capabilities, shared tenancy and burst CPU.",
  database: "Tuned for managed database engines with production-grade settings.",
  storage: "Large disks for S3-compatible object storage.",
  gpu: "NVIDIA hardware for model hosting; drivers and the runtime are managed.",
  k8s: "Joined to a cluster — workloads arrive through its control plane.",
  build: "Compiles images for other servers; runs no long-lived workloads.",
};

/** Types offered when connecting a NEW server. */
export const CONNECTABLE_SERVER_TYPES: ServerType[] = ["general", "vps", "database", "storage", "gpu", "build"];

/** Why a server type can't host anything, for an honest empty state. */
export const HOSTS_NOTHING_REASON: Partial<Record<ServerType, string>> = {
  k8s: "Cluster nodes receive workloads from the cluster's control plane, not directly.",
  build: "Build servers compile images and push them to a registry; they run no workloads.",
};

/** The availability matrix, server-first. */
export const SERVER_TYPE_HOSTS: Record<ServerType, ResourceKind[]> = {
  general: ["app", "postgres", "mysql", "mongodb", "redis"],
  vps: ["app", "postgres", "mysql", "mongodb", "redis"],
  database: ["postgres", "mysql", "mongodb", "redis"],
  storage: ["s3"],
  gpu: ["llm", "app"],
  k8s: [],
  build: [],
};

/** The same matrix, kind-first — what the deploy wizard asks. */
export const ALLOWED_SERVER_TYPES: Record<ResourceKind, ServerType[]> = {
  app: ["general", "vps", "gpu"],
  postgres: ["general", "vps", "database"],
  mysql: ["general", "vps", "database"],
  mongodb: ["general", "vps", "database"],
  redis: ["general", "vps", "database"],
  s3: ["storage"],
  llm: ["gpu"],
};

/** Kinds a Kubernetes cluster refuses to host, in catalog order.
 *
 *  The other half of "where can this run": the matrix above answers it for
 *  servers, this answers it for clusters. It is rendered from the control
 *  plane's own list (store.ClusterExcludedKinds) rather than restated, because
 *  the runtime answer travels with the cluster listing and demo mode has no
 *  control plane to ask — an empty list there would offer a cluster as a target
 *  for a database the API refuses. */
export const CLUSTER_EXCLUDED_KINDS: ResourceKind[] = ["postgres", "mysql", "mongodb", "redis", "s3", "llm"];

/** Billing weight per server type — what a server costs to MANAGE, never
 *  what the hardware costs; customers always bring their own infrastructure. */
export const SERVER_UNIT_WEIGHTS: Record<ServerType, number> = {
  general: 1,
  vps: 1,
  database: 1,
  storage: 1,
  gpu: 4,
  k8s: 2,
  build: 1,
};

/** Weight of an unknown/legacy type: bill as an ordinary server, never zero. */
export const DEFAULT_UNIT_WEIGHT = 1;
/** Price of one unit per month. */
export const UNIT_PRICE = 5;
/** Units included for free. Three ordinary servers still cost nothing. */
export const FREE_TIER_UNITS = 3;
export const CURRENCY = "EUR";

/** Distros the hardened onboarding path accepts. */
export const SUPPORTED_DISTROS: { id: string; label: string }[] = [
  { id: "ubuntu-22.04", label: "Ubuntu 22.04 LTS" },
  { id: "ubuntu-24.04", label: "Ubuntu 24.04 LTS" },
  { id: "debian-12", label: "Debian 12" },
];

/** What each managed database kind is provisioned as.
 *
 *  Rendered from store.dbEngines rather than restated, because demo mode kept a
 *  second copy and every value in it had drifted: postgres:17-alpine against a
 *  control plane pinned to 16.6 — a MAJOR version someone plans around — plus
 *  mysql:8.4 for 8.4.4, mongo:8 for 7.0.16 and redis:7-alpine for 7.4.2. Both
 *  panels print the value verbatim under a label reading "Engine", so the demo
 *  was not illustrating the product, it was describing a different one. */
export const DB_ENGINE_CATALOG: Record<DatabaseEngine, DatabaseEngineSpec> = {
  postgres: {
    engine: "postgres",
    image: "postgres:16.6",
    urlTemplate: "postgresql://{username}:{password}@{host}:{port}/{database}",
  },
  mysql: {
    engine: "mysql",
    image: "mysql:8.4.4",
    urlTemplate: "mysql://{username}:{password}@{host}:{port}/{database}",
  },
  mongodb: {
    engine: "mongodb",
    image: "mongo:7.0.16",
    urlTemplate: "mongodb://{username}:{password}@{host}:{port}/?authSource=admin",
  },
  redis: {
    engine: "redis",
    image: "redis:7.4.2",
    urlTemplate: "redis://:{password}@{host}:{port}/0",
  },
};

/** The database kinds, in catalog order. */
export const DB_ENGINE_KINDS: DatabaseEngine[] = ["postgres", "mysql", "mongodb", "redis"];

/** The object-storage engines, same story: the demo advertised
 *  minio/minio:latest and chrislusf/seaweedfs:latest, and the agent's image
 *  policy REFUSES a floating tag ("the floating 'latest' tag is not permitted"),
 *  so the demo was advertising images the product would decline to run. */
export const S3_ENGINE_CATALOG: Record<S3Engine, S3EngineSpec> = {
  minio: {
    engine: "minio",
    image: "minio/minio:RELEASE.2025-04-22T22-12-26Z",
    endpointTemplate: "http://{host}:{port}",
  },
  seaweedfs: {
    engine: "seaweedfs",
    image: "chrislusf/seaweedfs:3.94@sha256:d8ab8284bf4fd221e3cbf25f114f2f317c5bc942b1df032c43cc9d7bfe9bb1c6",
    endpointTemplate: "http://{host}:{port}",
  },
};

export const S3_ENGINE_NAMES: S3Engine[] = ["minio", "seaweedfs"];
/** What an s3 resource provisions when its spec names no engine. */
export const DEFAULT_S3_ENGINE: S3Engine = "minio";

/** The inference runtimes, in the order the picker offers them (the same
 *  order GET /llm/engines answers with). */
export const LLM_ENGINE_NAMES: LLMEngine[] = ["vllm", "ollama"];
/** What an llm resource is served by when its spec names no runtime — and
 *  therefore what the wizard must send for a model whose card did not resolve. */
export const DEFAULT_LLM_ENGINE: LLMEngine = "vllm";

/** Every alert event, in the order the control plane serves them
 *  (GET /orgs/{id}/alert-channels answers with exactly this list). The rules
 *  editor renders the runtime list, not this one — a dashboard talking to a
 *  newer control plane must still show an event it has never heard of — but
 *  this is what its label map is keyed on, so the labels cannot fall behind
 *  the vocabulary in silence. */
export const ALERT_EVENTS: AlertEvent[] = ["server_unreachable", "server_recovered", "decommission_timed_out", "dsd_apply_failed", "deploy_failed", "backup_failed", "verify_failed", "cert_failed", "cert_expiring", "payment_failed"];

/** The first mesh-bound host port the control plane's per-server allocator
 *  hands out (store.MeshPortBase). A managed engine is reachable on an
 *  ALLOCATED port from here up — never on the engine's container port, which is
 *  what demo mode used to print. "Your Postgres is on 5432" is the one sentence
 *  a connection panel must not teach about a product that hands out 15000+. */
export const MESH_PORT_BASE = 15000;

/** The model-sizing constants, from cp/internal/hf/sizing.go.
 *
 *  Demo mode has no control plane to ask, so its model cards carry the VRAM
 *  figures the control plane would have answered with. They were evaluated by
 *  hand, once, and the demo's own tests asserted them against themselves — so
 *  moving UtilizationCap to 0.85 or KVActivationFactor to 1.30 left every suite
 *  green while the demo went on telling evaluators a model needs ~21.4 GB
 *  against a product now saying ~22.7 GB (SIGMA-279). A prospect sizes a GPU
 *  purchase from that number.
 *
 *  These are NOT for computing a requirement at runtime: outside demo mode the
 *  control plane sends the byte count and the dashboard compares it, because
 *  two implementations of one formula are two answers to one question. They
 *  exist so the recorded fixtures can be checked against the arithmetic that
 *  produced them. */
export const VRAM_KV_ACTIVATION_FACTOR = 1.2;
export const VRAM_UTILIZATION_CAP = 0.9;
/** FormatVRAM's band boundaries: whole MB below the first, tenths of a GB
 *  below the second, whole GB rounded up at or above it. */
export const VRAM_FORMAT_MB_CEILING = 1000;
export const VRAM_FORMAT_TENTH_CEILING_GB = 100;

/** Whether a server type may host a resource kind. */
export function canHost(server: ServerType, kind: ResourceKind): boolean {
  return (SERVER_TYPE_HOSTS[server] ?? []).includes(kind);
}

/** Label for a server type that may not be one — CP rows carry plain strings,
 *  and an unknown type must render as itself rather than as "undefined". */
export function serverTypeLabel(type: string): string {
  return SERVER_TYPE_LABELS[type as ServerType] ?? type;
}

/** Label for a resource kind that may not be one. */
export function resourceKindLabel(kind: string): string {
  return RESOURCE_KIND_LABELS[kind as ResourceKind] ?? kind;
}

/** The kinds inside a category, in catalog order. Never empty. */
export function kindsInCategory(id: ResourceCategoryId): ResourceKind[] {
  return RESOURCE_CATEGORY_CATALOG[id].kinds;
}

/** The category a kind sits in, or null for a string that is not a kind —
 *  restored drafts and CP rows carry plain strings. */
export function categoryForKind(kind: string): ResourceCategoryId | null {
  return KIND_CATEGORY[kind as ResourceKind] ?? null;
}

/** Whether a kind may be deployed INSIDE a cluster. Takes a plain string, and
 *  answers true for one that is not a kind at all, because that is what the
 *  control plane answers: ClusterKindAllowed reads a DENY list, so anything not
 *  on it is allowed and the create call is the thing that rejects a nonsense
 *  kind. A stricter answer here would refuse targets the API would have taken. */
export function clusterCanHost(kind: string): boolean {
  return !CLUSTER_EXCLUDED_KINDS.includes(kind as ResourceKind);
}

/** Billing weight of a server type. An unknown type bills as an ordinary
 *  server, never as free: a typo must not silently zero out a bill. */
export function serverUnitWeight(type: string): number {
  return SERVER_UNIT_WEIGHTS[type as ServerType] ?? DEFAULT_UNIT_WEIGHT;
}

export function isServerType(value: string): value is ServerType {
  return value in SERVER_CATALOG;
}

export function isResourceKind(value: string): value is ResourceKind {
  return value in RESOURCE_KIND_LABELS;
}

/** Whether a resource kind is provisioned as a managed database engine. Takes a
 *  plain string: CP rows and restored drafts carry one, and a kind that is not
 *  an engine is simply not a database. */
export function isDatabaseEngine(kind: string): kind is DatabaseEngine {
  return kind in DB_ENGINE_CATALOG;
}

/** Whether a name is an object-storage engine this control plane provisions. */
export function isS3Engine(engine: string): engine is S3Engine {
  return engine in S3_ENGINE_CATALOG;
}

/** Fills a connection template in ONE pass, so a credential that happens to
 *  contain "{host}" is never re-read as a placeholder. The Go half
 *  (DBEngineDef.ConnectionURL) substitutes the same way, which is what makes
 *  one template render one string on both sides. */
function fillTemplate(template: string, parts: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) =>
    key in parts ? String(parts[key]) : whole
  );
}

/** The engine's canonical connection string.
 *
 *  The port belongs to the RESOURCE, not to the engine: a managed database is
 *  published on the mesh port its server allocated (MESH_PORT_BASE and up), and
 *  the container port never appears in a URL anyone dials. */
export function databaseConnectionUrl(
  engine: DatabaseEngine,
  parts: {
    username: string;
    password: string;
    host: string;
    port: number;
    database: string;
  }
): string {
  return fillTemplate(DB_ENGINE_CATALOG[engine].urlTemplate, parts);
}

/** The S3 API endpoint a client dials, on the same allocated mesh port. An
 *  empty host means the server has not finished mesh enrollment, and there is
 *  no endpoint to show yet — the control plane answers with nothing there too,
 *  rather than a URL pointing at no address. */
export function s3EndpointUrl(engine: S3Engine, host: string, port: number): string {
  if (!host) return "";
  return fillTemplate(S3_ENGINE_CATALOG[engine].endpointTemplate, { host, port });
}

/** hf.RequiredVRAMBytes: weights, plus what else lives on the card, over the
 *  share of it vLLM will actually allocate. Zero parameters means "unsized",
 *  which is the value that turns the fit check OFF everywhere downstream — it
 *  is never a model that needs no memory. */
export function requiredVramBytes(parameters: number, bytesPerParam: number): number {
  if (parameters <= 0 || bytesPerParam <= 0) return 0;
  const weights = parameters * bytesPerParam;
  return Math.ceil((weights * VRAM_KV_ACTIVATION_FACTOR) / VRAM_UTILIZATION_CAP);
}

/** hf.FormatVRAM: the one string both sides show, e.g. "~21.4 GB". Decimal GB,
 *  because the number being compared against is the one printed on the card.
 *  Zero renders as the empty string — an unsized model has no size to show, and
 *  "~0 GB" is a number that lies. */
export function formatVram(bytes: number): string {
  if (bytes <= 0) return "";
  // The unit is chosen from the ROUNDED figure: 999999999 bytes is under a
  // gigabyte and rounds to 1000 MB, which is a gigabyte spelled the long way.
  const mb = Math.round(bytes / 1e6);
  if (mb < VRAM_FORMAT_MB_CEILING) return `~${Math.max(1, mb)} MB`;
  const gb = bytes / 1e9;
  if (gb < VRAM_FORMAT_TENTH_CEILING_GB) return `~${gb.toFixed(1)} GB`;
  return `~${Math.ceil(gb)} GB`;
}
