-- SIGMA-365: grandfather the accounts that predate email verification.
--
-- Verification used to be opt-in, because no SMTP transport was bundled and
-- turning it on would have stranded every sign-up at an unsendable link. It now
-- defaults ON wherever mail can actually be delivered (lib/auth.ts reads
-- mailDelivers()), which means an existing install acquires the requirement the
-- moment its operator sets SMTP_HOST + SMTP_FROM — a change they make to FIX
-- their mail, with no reason to expect it touches sign-in.
--
-- Every row in `user` carries email_verified = false at that moment: the column
-- defaults false and, with verification off, nothing ever set it. So on the next
-- boot better-auth refuses every existing user at /sign-in/email with
-- EMAIL_NOT_VERIFIED — including the administrator who just wired the SMTP, and
-- including every account on a deployment whose users cannot be re-invited
-- because invites require a signed-in admin. The install locks itself.
--
-- Grandfathering is the honest resolution, not a compromise. These addresses are
-- unverified only in the sense that this deployment never asked; the accounts
-- already have full access under the rules they signed up under, so marking them
-- verified grants nothing that is not already granted. The alternative — asking
-- users to re-prove an address to keep an account they already hold — is a
-- password-reset storm on the day of an upgrade, and it fails closed on exactly
-- the deployments whose mail is least likely to work first time.
--
-- The cut is the migration itself: it runs once, so accounts created after this
-- point go through verification normally. On a fresh install the table is empty
-- and this is a no-op.
--
-- The NOT EXISTS is what keeps this from being a back door rather than a
-- migration. Unconditionally, it also verifies accounts on a deployment that had
-- ALREADY turned verification on — where an unverified row is not "we never
-- asked", it is "this person did not prove the address". `email_verified` is
-- load-bearing for exactly one control, the invite email-match in
-- server/actions/members.ts, and the whole point of that control is that someone
-- holding a leaked invite link cannot register the invited address and walk in.
-- Marking those rows verified would hand them the thing the control exists to
-- withhold.
--
-- A deployment that has been verifying has at least one verified account; a
-- deployment that never asked has none. That is the difference, it is visible in
-- the data, and it is the condition below.
--
-- The one case it decides "wrongly" is a deployment where verification was on
-- and NOBODY ever completed it. There, no account can sign in at all, so every
-- row is already locked out and grandfathering is the recovery rather than a
-- weakening.
UPDATE "user" SET "email_verified" = true
 WHERE "email_verified" = false
   AND NOT EXISTS (SELECT 1 FROM "user" WHERE "email_verified" = true);
