package k8s

// The agent half of the k8s.apply wire contract (SIGMA-338).
//
// Every other test in this package — including the real-Kubernetes e2e —
// builds its ApplySpec as a literal in the test body. That proves the renderer
// handles the value the test wrote down; it proves nothing about the value the
// control plane sends. The two structs (cp/internal/reconciler.k8sApplyOpSpec
// and this package's ApplySpec) are hand-mirrored across a module boundary that
// forbids an import, and nothing joined them: renaming the CP's `hosts` tag to
// `domains` drops every cluster ingress — a customer's domain 404s while the
// apply and the deployment both report success — and the whole cp module and
// the whole agent module stayed green.
//
// So the control plane's suite writes the specs it would actually send to
// cp/internal/reconciler/testdata/k8s_apply_specs.json, and this file decodes
// that file into ApplySpec with unknown fields REJECTED. A CP field the agent
// has no home for is now a decode failure here, and a field the CP stops
// setting is an assertion failure. The e2e (k8s_e2e_test.go) drives the same
// fixture through a real API server, so the manifest Kubernetes validates is
// the manifest the control plane would have caused.
//
// Reading across the module boundary is deliberate: the file is checked in and
// both modules live in one repository and one CI checkout. The alternative —
// a copy on each side — is the drift this is here to catch.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

const cpApplyFixturePath = "../../../cp/internal/reconciler/testdata/k8s_apply_specs.json"

type cpApplyCase struct {
	Name string
	OpID string
	Spec ApplySpec
}

// loadCPApplySpecs decodes every k8s.apply spec the control plane renders.
// Unknown fields are an error, not a shrug: silently ignoring a field the CP
// went to the trouble of sending is the exact failure this fixture exists for.
func loadCPApplySpecs(t *testing.T) []cpApplyCase {
	t.Helper()
	raw, err := os.ReadFile(cpApplyFixturePath)
	if err != nil {
		t.Fatalf("the control plane's k8s.apply fixture is unreadable: %v\n"+
			"It is generated by cp/internal/reconciler/k8s_fixture_test.go.", err)
	}
	var doc struct {
		Cases []struct {
			Name string          `json:"name"`
			OpID string          `json:"opId"`
			Spec json.RawMessage `json:"spec"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) == 0 {
		t.Fatal("no cases in the fixture — this guard would pass vacuously")
	}
	out := make([]cpApplyCase, 0, len(doc.Cases))
	for _, c := range doc.Cases {
		dec := json.NewDecoder(bytes.NewReader(c.Spec))
		dec.DisallowUnknownFields()
		var spec ApplySpec
		if err := dec.Decode(&spec); err != nil {
			t.Fatalf("%s (%s): the control plane sends a field this agent has no home for: %v\n"+
				"Either ApplySpec is missing it or a json tag drifted between the two modules.\n%s",
				c.Name, c.OpID, err, c.Spec)
		}
		out = append(out, cpApplyCase{Name: c.Name, OpID: c.OpID, Spec: spec})
	}
	return out
}

// caseID names a fixture case in a failure message. The op id alone repeats
// across the compose graph's services, so both are printed.
func caseID(c cpApplyCase) string { return fmt.Sprintf("%s/%s", c.Name, c.OpID) }

// cpApplySpecs returns every workload the control plane renders for one fixture
// case, in the order it rendered them.
func cpApplySpecs(t *testing.T, name string) []ApplySpec {
	t.Helper()
	var out []ApplySpec
	for _, c := range loadCPApplySpecs(t) {
		if c.Name == name {
			out = append(out, c.Spec)
		}
	}
	if len(out) == 0 {
		t.Fatalf("no control-plane fixture case named %q", name)
	}
	return out
}

// cpApplySpec returns one workload: the case's only one, or the one whose
// Compose service matches. Fails rather than guessing, so a fixture that grows
// a second workload cannot silently change which spec a test is asserting on.
func cpApplySpec(t *testing.T, name, service string) ApplySpec {
	t.Helper()
	specs := cpApplySpecs(t, name)
	if service == "" {
		if len(specs) != 1 {
			t.Fatalf("fixture case %q renders %d workloads; name the service", name, len(specs))
		}
		return specs[0]
	}
	for _, s := range specs {
		if s.Service == service {
			return s
		}
	}
	t.Fatalf("fixture case %q has no service %q", name, service)
	return ApplySpec{}
}

// TestCPRenderedSpecsAreApplyable runs the control plane's own output through
// the agent's validation and renderer. This is the half of the guard that does
// not need a cluster, so it runs on every PR rather than only in the k3s job.
func TestCPRenderedSpecsAreApplyable(t *testing.T) {
	for _, c := range loadCPApplySpecs(t) {
		t.Run(caseID(c), func(t *testing.T) {
			spec := c.Spec

			// The names the agent will refuse outright.
			if !dnsName.MatchString(spec.Name) {
				t.Fatalf("workload name %q would be rejected by the agent", spec.Name)
			}
			if !dnsName.MatchString(spec.Namespace) {
				t.Fatalf("namespace %q would be rejected by the agent", spec.Namespace)
			}
			if spec.Image == "" {
				t.Fatal("no image: the node has nothing to run")
			}
			// A Deployment with zero replicas is accepted by the API server and
			// runs nothing. The renderer floors it at 1, so this is about the
			// control plane's intent arriving intact rather than about the YAML.
			if spec.Replicas < 1 {
				t.Errorf("replicas = %d — the control plane asked for a workload that can never have a pod",
					spec.Replicas)
			}
			// Every workload the CP renders lists itself in the prune set;
			// missing that, the agent deletes the manifest it just wrote.
			if len(spec.Workloads) > 0 {
				found := false
				for _, w := range spec.Workloads {
					if w == spec.Name {
						found = true
					}
				}
				if !found {
					t.Errorf("workloads %v does not contain this workload %q — the agent would prune it away",
						spec.Workloads, spec.Name)
				}
			}

			manifest, err := renderManifests(spec, spec.Namespace, nil, nil)
			if err != nil {
				t.Fatalf("the control plane's spec does not render: %v", err)
			}
			// The values the deploy depends on have to reach the YAML, not just
			// the struct.
			if !strings.Contains(manifest, "image: "+yamlStr(spec.Image)) {
				t.Errorf("image %q missing from the manifest", spec.Image)
			}
			if !strings.Contains(manifest, fmt.Sprintf("replicas: %d", spec.Replicas)) {
				t.Errorf("replicas %d missing from the manifest", spec.Replicas)
			}
			for _, p := range spec.Ports {
				if !strings.Contains(manifest, fmt.Sprintf("containerPort: %d", p)) {
					t.Errorf("port %d missing from the manifest", p)
				}
			}
			for _, h := range spec.Hosts {
				// An attached domain that renders no Ingress rule is the
				// `hosts`→`domains` failure: a green deploy nobody can reach.
				if !strings.Contains(manifest, "host: "+yamlStr(h)) {
					t.Errorf("host %q attached by the control plane has no ingress rule", h)
				}
			}
		})
	}
}

// TestCPFixtureCoversTheInterestingFields keeps the fixture from decaying into
// a set of cases that exercises nothing. Without this, deleting the compose
// case (or the domains from every case) would leave the guard above green while
// covering strictly less.
func TestCPFixtureCoversTheInterestingFields(t *testing.T) {
	var sawHosts, sawPorts, sawEnv, sawSecretRefs, sawRegistry, sawService bool
	for _, c := range loadCPApplySpecs(t) {
		sawHosts = sawHosts || len(c.Spec.Hosts) > 0
		sawPorts = sawPorts || len(c.Spec.Ports) > 0
		sawEnv = sawEnv || len(c.Spec.Env) > 0
		sawSecretRefs = sawSecretRefs || len(c.Spec.SecretRefs) > 0
		sawRegistry = sawRegistry || c.Spec.RegistryHost != ""
		sawService = sawService || c.Spec.Service != ""
	}
	for _, f := range []struct {
		field string
		ok    bool
	}{
		{"hosts", sawHosts}, {"ports", sawPorts}, {"env", sawEnv},
		{"secretRefs", sawSecretRefs}, {"registryHost", sawRegistry},
		{"service (a Compose workload)", sawService},
	} {
		if !f.ok {
			t.Errorf("no control-plane fixture case sets %s — that field is unguarded", f.field)
		}
	}
}
