package store

// Renders the canonical server catalog as the dashboard's TypeScript module.
//
// The dashboard used to keep its own copy of the type list, the availability
// matrix and the billing weights, reconciled by a test that regex-parsed this
// package's Go source. That test only proved the web knew about types the CP
// had; it never noticed the API's own fourth copy, which is how the connect
// dialog ended up offering VPS and Build buttons that answered 400.
//
// Generating instead of mirroring keeps the property the endpoint approach
// would have thrown away: the emitted unions are real TypeScript literal types,
// so a label map that forgets a new server type fails `tsc --noEmit` at the
// point of the omission rather than rendering `undefined` in production. Data
// arriving at runtime as string[] cannot narrow a union and cannot do that.
//
// Nothing here knows any server type by name — adding one stays an edit to
// server_catalog.go alone.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// tsCatalogHeader explains the file to whoever opens it having never seen this
// mechanism; %s is the digest of the Go source it was rendered from.
const tsCatalogHeader = `// Code generated by cp/cmd/gen-server-catalog. DO NOT EDIT.
//
// The dashboard's server-type vocabulary — the type list, the resource-kind ×
// server-type availability matrix, the billing weights and the per-type
// enrollment requirements — is RENDERED from the control plane's canonical
// catalog at cp/internal/store/server_catalog.go.
//
// Editing this file by hand re-creates the defect SIGMA-198 removed: a
// dashboard offering server types the API rejects. Change the Go catalog and
// regenerate:
//
//     cd cp && go generate ./...

/**
 * sha256 of the Go catalog this file was rendered from.
 *
 * web/src/lib/hosting.test.ts recomputes it, so a control-plane edit that never
 * went through the generator fails the web suite instead of quietly shipping a
 * stale dashboard.
 */
export const CATALOG_SOURCE_SHA256 = %s;
`

// tsCatalogHelpers are the accessors every consumer needs. Emitted verbatim
// because they are boilerplate over the generated tables, and because a
// hand-written wrapper module beside the generated one is exactly the second
// place a copy grows back into.
const tsCatalogHelpers = `
/** Whether a server type may host a resource kind. */
export function canHost(server: ServerType, kind: ResourceKind): boolean {
  return (SERVER_TYPE_HOSTS[server] ?? []).includes(kind);
}

/** Label for a server type that may not be one — CP rows carry plain strings,
 *  and an unknown type must render as itself rather than as "undefined". */
export function serverTypeLabel(type: string): string {
  return SERVER_TYPE_LABELS[type as ServerType] ?? type;
}

/** Label for a resource kind that may not be one. */
export function resourceKindLabel(kind: string): string {
  return RESOURCE_KIND_LABELS[kind as ResourceKind] ?? kind;
}

/** Billing weight of a server type. An unknown type bills as an ordinary
 *  server, never as free: a typo must not silently zero out a bill. */
export function serverUnitWeight(type: string): number {
  return SERVER_UNIT_WEIGHTS[type as ServerType] ?? DEFAULT_UNIT_WEIGHT;
}

export function isServerType(value: string): value is ServerType {
  return value in SERVER_CATALOG;
}

export function isResourceKind(value: string): value is ResourceKind {
  return value in RESOURCE_KIND_LABELS;
}
`

// RenderTypeScript renders the catalog module. srcSHA is the digest of
// server_catalog.go; both the generator and the staleness test supply it from
// the file on disk, so the emitted digest always describes real source.
func RenderTypeScript(srcSHA string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, tsCatalogHeader, tsString(srcSHA))

	types := ServerTypes()
	kinds := ResourceKinds()

	b.WriteString("\n")
	fmt.Fprintf(&b, "export type ServerType =\n%s;\n\n", tsUnion(types))
	fmt.Fprintf(&b, "export type ResourceKind =\n%s;\n\n", tsUnion(kinds))
	fmt.Fprintf(&b, "export type RequirementId =\n%s;\n\n", tsUnion(requirementIDs()))

	b.WriteString(`/** One precondition a host must meet to enroll as a type. The fact field names
 *  the agent-reported datum it is checked against, so a host that never
 *  reported it can be told which fact is missing instead of simply failing. */
export type ServerRequirement = {
  id: RequirementId;
  fact: string;
  text: string;
};

export type GpuRequirement = { vendor: string; driver: boolean };

export type ServerRequirements = {
  distros: string[];
  arches: string[];
  /** Decimal-byte floor on total disk; 0 means no floor. */
  minDiskBytes: number;
  gpu: GpuRequirement | null;
  /** The same sentences the control plane will reject a host with. */
  checks: ServerRequirement[];
};

export type ServerTypeSpec = {
  type: ServerType;
  label: string;
  hint: string;
  hosts: ResourceKind[];
  /** Why hosts is empty, so the UI never shows an unexplained dead end. */
  hostsNothingReason: string;
  /** Offered when connecting a NEW server. UI guidance, not an API rule — the
   *  control plane accepts every type in this catalog. */
  connectable: boolean;
  unitWeight: number;
  requires: ServerRequirements;
};

`)

	// The catalog itself.
	b.WriteString("export const SERVER_CATALOG: Record<ServerType, ServerTypeSpec> = {\n")
	for _, spec := range serverCatalog {
		b.WriteString("  " + spec.Type + ": {\n")
		fmt.Fprintf(&b, "    type: %s,\n", tsString(spec.Type))
		fmt.Fprintf(&b, "    label: %s,\n", tsString(spec.Label))
		fmt.Fprintf(&b, "    hint: %s,\n", tsString(spec.Hint))
		fmt.Fprintf(&b, "    hosts: %s,\n", tsStringArray(spec.Hosts))
		fmt.Fprintf(&b, "    hostsNothingReason: %s,\n", tsString(spec.HostsNothingReason))
		fmt.Fprintf(&b, "    connectable: %t,\n", spec.Connectable)
		fmt.Fprintf(&b, "    unitWeight: %d,\n", spec.UnitWeight)
		b.WriteString("    requires: {\n")
		fmt.Fprintf(&b, "      distros: %s,\n", tsStringArray(spec.Requires.Distros))
		fmt.Fprintf(&b, "      arches: %s,\n", tsStringArray(spec.Requires.Arches))
		fmt.Fprintf(&b, "      minDiskBytes: %d,\n", spec.Requires.MinDiskBytes)
		if spec.Requires.GPU == nil {
			b.WriteString("      gpu: null,\n")
		} else {
			fmt.Fprintf(&b, "      gpu: { vendor: %s, driver: %t },\n",
				tsString(spec.Requires.GPU.Vendor), spec.Requires.GPU.Driver)
		}
		b.WriteString("      checks: [\n")
		for _, req := range spec.Requires.List() {
			fmt.Fprintf(&b, "        { id: %s, fact: %s, text: %s },\n",
				tsString(string(req.ID)), tsString(req.Fact), tsString(req.Text))
		}
		b.WriteString("      ],\n")
		b.WriteString("    },\n")
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Every server type, in the order the dashboard presents them. */\n")
	fmt.Fprintf(&b, "export const SERVER_TYPES: ServerType[] = %s;\n\n", tsStringArray(types))
	fmt.Fprintf(&b, "export const RESOURCE_KINDS: ResourceKind[] = %s;\n\n", tsStringArray(kinds))

	b.WriteString("export const SERVER_TYPE_LABELS: Record<ServerType, string> = {\n")
	for _, spec := range serverCatalog {
		fmt.Fprintf(&b, "  %s: %s,\n", spec.Type, tsString(spec.Label))
	}
	b.WriteString("};\n\n")

	b.WriteString("export const RESOURCE_KIND_LABELS: Record<ResourceKind, string> = {\n")
	for _, k := range resourceKinds {
		fmt.Fprintf(&b, "  %s: %s,\n", k.Kind, tsString(k.Label))
	}
	b.WriteString("};\n\n")

	b.WriteString("/** One line explaining what each type is for, shown in the connect dialog. */\n")
	b.WriteString("export const SERVER_TYPE_HINTS: Record<ServerType, string> = {\n")
	for _, spec := range serverCatalog {
		fmt.Fprintf(&b, "  %s: %s,\n", spec.Type, tsString(spec.Hint))
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Types offered when connecting a NEW server. */\n")
	fmt.Fprintf(&b, "export const CONNECTABLE_SERVER_TYPES: ServerType[] = %s;\n\n",
		tsStringArray(ConnectableServerTypes()))

	b.WriteString("/** Why a server type can't host anything, for an honest empty state. */\n")
	b.WriteString("export const HOSTS_NOTHING_REASON: Partial<Record<ServerType, string>> = {\n")
	for _, spec := range serverCatalog {
		if spec.HostsNothingReason != "" {
			fmt.Fprintf(&b, "  %s: %s,\n", spec.Type, tsString(spec.HostsNothingReason))
		}
	}
	b.WriteString("};\n\n")

	b.WriteString("/** The availability matrix, server-first. */\n")
	b.WriteString("export const SERVER_TYPE_HOSTS: Record<ServerType, ResourceKind[]> = {\n")
	for _, spec := range serverCatalog {
		fmt.Fprintf(&b, "  %s: %s,\n", spec.Type, tsStringArray(spec.Hosts))
	}
	b.WriteString("};\n\n")

	b.WriteString("/** The same matrix, kind-first — what the deploy wizard asks. */\n")
	b.WriteString("export const ALLOWED_SERVER_TYPES: Record<ResourceKind, ServerType[]> = {\n")
	for _, k := range resourceKinds {
		fmt.Fprintf(&b, "  %s: %s,\n", k.Kind, tsStringArray(AllowedServerTypes(k.Kind)))
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Billing weight per server type — what a server costs to MANAGE, never\n" +
		" *  what the hardware costs; customers always bring their own infrastructure. */\n")
	b.WriteString("export const SERVER_UNIT_WEIGHTS: Record<ServerType, number> = {\n")
	for _, spec := range serverCatalog {
		fmt.Fprintf(&b, "  %s: %d,\n", spec.Type, spec.UnitWeight)
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Weight of an unknown/legacy type: bill as an ordinary server, never zero. */\n")
	fmt.Fprintf(&b, "export const DEFAULT_UNIT_WEIGHT = %d;\n", DefaultServerUnitWeight)
	b.WriteString("/** Price of one unit per month. */\n")
	fmt.Fprintf(&b, "export const UNIT_PRICE = %d;\n", BillingUnitPrice)
	b.WriteString("/** Units included for free. Three ordinary servers still cost nothing. */\n")
	fmt.Fprintf(&b, "export const FREE_TIER_UNITS = %d;\n", BillingFreeTier)
	fmt.Fprintf(&b, "export const CURRENCY = %s;\n\n", tsString(BillingCurrency))

	b.WriteString("/** Distros the hardened onboarding path accepts. */\n")
	b.WriteString("export const SUPPORTED_DISTROS: { id: string; label: string }[] = [\n")
	for _, d := range supportedDistroLabels {
		fmt.Fprintf(&b, "  { id: %s, label: %s },\n", tsString(d.ID), tsString(d.Label))
	}
	b.WriteString("];\n")

	b.WriteString(tsCatalogHelpers)
	return b.Bytes()
}

// requirementIDs is the closed set of precondition ids, in List()'s order.
func requirementIDs() []string {
	return []string{string(ReqDistro), string(ReqArch), string(ReqDisk), string(ReqGPU)}
}

// tsString renders a Go string as a TypeScript double-quoted literal. JSON's
// escaping is a strict subset of TS's, so encoding/json is the safe renderer
// rather than hand-rolled quoting.
func tsString(s string) string {
	b, err := json.Marshal(s)
	if err != nil { // impossible for a string; a panic here beats emitting junk
		panic("store: cannot render TS string: " + err.Error())
	}
	return string(b)
}

func tsStringArray(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	parts := make([]string, 0, len(items))
	for _, item := range items {
		parts = append(parts, tsString(item))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// tsUnion renders a literal union one member per line, which keeps the diff on
// adding a type to a single added line.
func tsUnion(items []string) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		parts = append(parts, "  | "+tsString(item))
	}
	return strings.Join(parts, "\n")
}
